using Abp.Domain.Entities.Auditing;
using System;
using System.Collections.Generic;

namespace Elicom.Entities
{
    public class SupplierOrder : FullAuditedEntity<Guid>
    {
        // Generated by our system, shared with supplier
        public string ReferenceCode { get; set; }

        // Seller / Reseller
        public long ResellerId { get; set; }

        public decimal TotalPurchaseAmount { get; set; }

        public string WarehouseAddress { get; set; }

        // Purchased, LinkedToOrder, Received, Settled
        public string Status { get; set; }

        // Optional link (filled later)
        public Guid? OrderId { get; set; }
        public virtual Order Order { get; set; }

        public virtual ICollection<SupplierOrderItem> Items { get; set; }
    }
}
