using Abp.Domain.Entities.Auditing;
using Elicom.Authorization.Users;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Elicom.Entities
{
    public class SupplierOrder : FullAuditedEntity<Guid>
    {
        // Generated by our system, shared with supplier
        public string ReferenceCode { get; set; }

        // Seller / Reseller
        public long ResellerId { get; set; }
        [ForeignKey(nameof(ResellerId))]
        public virtual User Reseller { get; set; }

        // The Supplier
        public long SupplierId { get; set; }

        public decimal TotalPurchaseAmount { get; set; }

        public string WarehouseAddress { get; set; }
        public string ShippingAddress { get; set; }
        public string CustomerName { get; set; }

        public string SourcePlatform { get; set; }

        // Purchased, LinkedToOrder, Received, Settled
        public string Status { get; set; }

        // Seller sets when shipping to Admin Hub
        public DateTime? ShipmentDate { get; set; }
        public string CarrierId { get; set; }
        public string TrackingCode { get; set; }

        // Optional link (filled later)
        public Guid? OrderId { get; set; }
        public virtual Order Order { get; set; }

        public virtual ICollection<SupplierOrderItem> Items { get; set; }
    }
}
